# settings.py
MODE_NORMAL = 1
MODE_HARD = 2

PLAYER_LIVES = 3
POINTS_FOR_FIGHT = 1
POINTS_FOR_KILLING = 5
MAX_RECORDS_NUMBER = 5

SCORE_FILE = 'scores.txt'

PAPER = 'Paper'
STONE = 'Stone'
SCISSORS = 'Scissors'

ALLOWED_ATTACKS = {
    '1': PAPER,
    '2': STONE,
    '3': SCISSORS
}

ATTACK_PAIRS_OUTCOME = {
    (PAPER, PAPER): 0,
    (PAPER, STONE): 1,
    (PAPER, SCISSORS): -1,
    (STONE, PAPER): -1,
    (STONE, STONE): 0,
    (STONE, SCISSORS): 1,
    (SCISSORS, PAPER): 1,
    (SCISSORS, STONE): -1,
    (SCISSORS, SCISSORS): 0
}
